default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{env_var('PG_PUBLIC_IP', 'not_set')}}"
      port: 5432
      user: "{{env_var('PG_USERNAME', 'username')}}"
      password: "{{env_var('PG_PASSWORD', 'password')}}"
      dbname: "{{env_var('PG_DB_NAME', 'jaffle_shop')}}"
      schema: "dbt_dev_{{env_var('DBT_DEV_NAME', 'yourname')}}"
      threads: 4
      connect_timeout: 10
    cicd:
      type: postgres
      host: "{{env_var('PG_HOSTNAME', 'localhost')}}"
      port: 5432
      user: "{{env_var('PG_USERNAME', 'TEST')}}"
      password: "{{env_var('PG_PASSWORD', 'TEST')}}"
      dbname: "{{env_var('PG_DB_NAME', 'jaffle_shop')}}"
      schema: "{{env_var('GITHUB_PR_SCHEMA', 'cicd')}}"
      threads: 4
      connect_timeout: 10
