name: CI_pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  CI_jobs:
    permissions:
      contents: read
      id-token: write # Needed to request OIDC token from GitHub

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      PG_USERNAME: ${{ secrets.PG_USERNAME }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
      GITHUB_PR_SCHEMA: "ci_pr_${{github.event.pull_request.number}}"
      PG_PUBLIC_IP: ${{secrets.PG_PUBLIC_IP}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changed Files
        id: file_changes
        uses: tj-actions/changed-files@v46.0.3

      # - name: Check env var GITHUB_CONTEXT
      #   run: echo '${{ toJson(github) }}'

      - name: Print info
        run: |
          echo PR number: "$GITHUB_PR_SCHEMA"
          echo Changed files: '${{ steps.file_changes.outputs.all_changed_files}}'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install python
        run: uv python install

      - name: Install project dependencies
        run: uv sync

      - name: Run pre-commit on changed files
        if: steps.file_changes.outputs.any_changed == 'true'
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ steps.file_changes.outputs.all_changed_files }}

      - name: Authenticate to Google Cloud with Workload Identity Federation
        id: auth_gcloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/321604249783/locations/global/workloadIdentityPools/dbt-github-actions-pool/providers/github-provider'
          service_account: 'dbt-github-actions-sa@ae-dbt-ci-2025.iam.gserviceaccount.com'
          token_format: 'access_token'  # Outputs access_token

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
